[[main]]
  identifier = "AWS"
  name = "AWS"
  url = "aws"
  weight = 1

[[main]]
  identifier = "Azure"
  name = "Azure"
  url = "azure"
  weight = 2

[[main]]
  identifier = "GCP"
  name = "GCP"
  url = "gcp"
  weight = 3

[[main]]
  identifier = "About"
  name = "About"
  url = "about"
  weight = 4
